apiVersion: v1
kind: Namespace
metadata:
  name: catoso
  labels:
    name: catoso
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: zerozerocat
 namespace: catoso
spec:
 replicas: 1
 selector:
   matchLabels:
     app: zerozerocat
 template:
   metadata:
     labels:
       app: zerozerocat
   spec:
     containers:
       - name: zerozerocat
         image: pedromol/zerozerocat
         args:
          - /app/index.js
         command:
          - node
         env:
          - name: BUCKET_ACCESS_KEY_ID
            value : 'xxxxxxxx'
          - name: BUCKET_SECRET_ACCESS_KEY
            value : 'xxxxxxx'
          - name: BUCKET_ENDPOINT
            value : 'http://xxxx.xxxx:xxxx/'
          - name: BUCKET_REGION
            value : 'us-east-1'
          - name: BUCKET_NAME
            value : 'zerozerocat'
          - name: MIN_DETECTIONS
            value : '5'
          - name: NAME_MAPPINGS
            value : 'xxxx,yyyy,zzzz'
          - name: TELEGRAM_TOKEN
            value : 'xxxxxxxx'
          - name: TELEGRAM_CHAT
            value : 'xxxxxx'
          - name: HTTP_PORT
            value : 'xxxxxx'
---
apiVersion: v1
kind: Service
metadata:
 name: zerozerocat
 namespace: catoso
 labels:
   app: zerozerocat
spec:
 ports:
 - port: 80
   targetPort: 8080
 selector:
   app: zerozerocat
