FROM pedromol/zerozerocat:base

ENV NODE_PATH=/usr/lib/node_modules

RUN mkdir -p /app

COPY package* /app/
COPY tsconfig* /app/
COPY nest-cli.json /app/
COPY models/haarcascade_frontalcatface_extended.xml /app/models/

WORKDIR /app
RUN npm i --production --prune && \
    npm i -g @nestjs/cli
