FROM pedromol/zerozerocat:base

ENV NODE_PATH=/usr/lib/node_modules

RUN mkdir -p /app

COPY package.json /app
COPY package-lock.json /app
COPY haarcascade_frontalcatface.xml /app
COPY haarcascade_frontalcatface_extended.xml /app

WORKDIR /app
RUN npm i
